config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :friends
  root 'friends#index'

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
# frozen_string_literal: true

class Friend < ApplicationRecord
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :first_name, :last_name, :address, presence: true
  validates :email, presence: true, uniqueness: true,
                    format: { with: EMAIL_REGEX, message: 'must be a valid email address' }

  def self.order_alphabetical
    order(:first_name)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
# frozen_string_literal: true

class FriendsController < ApplicationController
  before_action :set_friend, only: %i[show edit update destroy]

  def index
    # for _btn_new_friend
    @friends = Friend.order_alphabetical
  end

  def show; end

  def new
    @friend = Friend.new
  end

  def edit; end

  def create
    @friend = Friend.new(friend_params)

    if @friend.save
      flash[:notice] = 'Friend was successfully created.'
      redirect_to @friend
    else
      flash[:alert] = 'There was an error creating the friend.'
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @friend.update(friend_params)
      flash[:notice] = 'Friend was successfully updated.'
      redirect_to @friend
    else
      flash[:alert] = 'There was an error updating the friend.'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @friend.destroy!
    flash[:alert] = 'Friend was successfully destroyed.'
    redirect_to friends_path, status: :see_other
  end

  private

  def set_friend
    @friend = Friend.find(params[:id])
  end

  def friend_params
    params.require(:friend).permit(:first_name, :last_name, :email, :address)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/friends_helper.rb
# frozen_string_literal: true

module FriendsHelper
end

app/views/friends/_form.html.erb
<%= simple_form_for @friend do |form| %>
  <%= form.input :first_name, label: false,
      placeholder: "First name", error: @friend.errors[:first_name].join(", ")
  %>
  <%= form.input :last_name, label: false,
      placeholder: "Last name", error: @friend.errors[:last_name].join(", ")
  %>
  <%= form.input :email, label: false,
      placeholder: "Email", error: @friend.errors[:email].join(", ")
  %>
  <%= form.input :address, label: false,
      placeholder: "Address", error: @friend.errors[:address].join(", ")
  %>
  <%= form.button :submit, class: "btn btn-primary bt-sm" %>
<% end %>

app/views/friends/edit.html.erb
<div class="col-6">
  <div class="d-flex justify-content-between">
      <h2>Editing friend</h2>
      <%= link_to "Back", friend_path, class: "btn btn-warning align-self-start" %>
  </div>
  <div class="mt-3">
    <%= render "form", friend: @friend %>
  </div>
</div>

app/views/friends/index.html.erb
<table class="table table-striped">
  <thead class="table-dark">
    <tr>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
      <th scope="col">Address</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>
  <tbody class="table-hover">
    <% @friends.each do |friend| %>
      <tr id="friends">
        <td><%= "#{friend.first_name}" %></td>
        <td><%= "#{friend.last_name}"  %></td>
        <td><%= "#{friend.email}"      %></td>
        <td><%= "#{friend.address}"    %></td>
        <td><%= link_to "Show", friend_path(friend),
                class:"btn btn-primary btn-sm" %>
        </td>
        <td><%= link_to "Edit", edit_friend_path(friend),
                class: "btn btn-warning btn-sm" %>
        </td>
        <td><%= render "shared/btn_delete_friend",
                locals: { friendPath: friend_path(friend) }
            %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>

app/views/friends/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @friend.first_name %>
    <%= @friend.last_name %>
  </h1>
  <p class="lead">
    <%= @friend.email %> | <%= @friend.address %>
  </p>
  <br/>

  <div class="d-flex">
    <%= link_to "Edit", edit_friend_path(@friend),
        class: "btn btn-warning me-2"
    %>
    <%= render "shared/btn_delete_friend",
        locals: { friendPath: friend_path(@friend) }
    %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFriends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/header" %>
    <div class="container mt-5">
      <%= render "shared/alert" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_alert.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= flash[:alert] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_btn_delete_friend.html.erb
<%= link_to "Delete", "#",
    class: "btn btn-danger btn-sm",
    data: { bs_toggle: 'modal', bs_target: '#deleteModal' }
%>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        Are you sure you want to delete?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <%= button_to 'Delete', locals[:friendPath], method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Friend App', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "New Friend", new_friend_path, class:"nav-link" %>
        </li>
      </ul>

      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>